name = "spectux-leads-api"
main = "index.js" # Of waar je worker code precies staat
compatibility_date = "2024-03-04"

# 1. Jouw D1 Database koppeling (Plak hier de output van Stap 1)
[[d1_databases]]
binding = "DB"
database_name = "sp_leads"
database_id = "5c0ac500-9529-44c9-b951-63125f1825c9"

[triggers]
crons = ["0 3 * * *"]
